# Season Leaderboard 
   - Load a season’s box‐score CSV  
   - Compute and sort by advanced metrics:  
     - **PER**, **Usage Rate**, **TS%**  
   - Display top 10 with `df.nlargest(10, 'TS%')`


# PER
- normalized stat to compare different players across different teams 
- summarizes a player's overall performance by considering both positive and negative contributions to a game
- per-minute statistic
  - adjusted for how much time a player is on the court
  - also pace-adjusted to account for different team tempo


# USAGE RATE
- estimates the percentage of a team's possessions a player uses while they are on the court
-  quantifies a player's contribution to a team's offensive possessions
- OFFENSIVE

# TS% 
- player's shooting efficiency that considers all types of shots (2-pointers, 3-pointers, and free throws)
- more comprehensive than FG% becuase it takes 3pts in account

In [1]:
#Learn to get any data into a dataframe using nba_api/other methods

In [2]:

import pandas as pd

In [3]:
from nba_api.stats.endpoints import LeagueDashPlayerStats

#1. build params 
params = { 
    "season": "2016-17",
    "season_type_all_star": "Regular Season",
    "per_mode_detailed": "PerGame",
    "plus_minus": "N",
    "pace_adjust": "N",
    "rank": "N",
}

#2. get the data (pass params ass arguent and use get_data_frames())
endpoint = LeagueDashPlayerStats(**params)
df_list  = endpoint.get_data_frames()
player_stats_df = df_list[0]

In [4]:
#3. turn into a df
stats = pd.DataFrame(player_stats_df)
stats# final dataframe

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,TEAM_COUNT
0,52453,None,None,NaN,None,NaN,8,4,4,0.500,...,467,811,10,72,1122,84,227,39,85,1
1,52456,None,None,NaN,None,NaN,8,4,4,0.500,...,86,55,46,205,1122,269,227,39,248,1
2,52458,None,None,NaN,None,NaN,8,4,4,0.500,...,162,258,291,473,938,722,512,39,623,1
3,52449,None,None,NaN,None,NaN,8,4,4,0.500,...,467,642,1013,684,902,776,512,39,725,1
4,52455,None,None,NaN,None,NaN,8,4,4,0.500,...,937,301,366,875,702,717,512,39,781,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1581,203897,Zach LaVine,Zach,1.610613e+09,MIN,22.0,47,16,31,0.340,...,185,583,493,99,1190,247,512,39,179,1
1582,2216,Zach Randolph,Zach,1.610613e+09,MEM,35.0,73,38,35,0.521,...,150,819,378,274,515,307,27,39,326,1
1583,2585,Zaza Pachulia,Zaza,1.610613e+09,GSW,33.0,70,58,12,0.829,...,534,502,554,910,101,652,193,39,730,1
1584,1626580,Zeke Upshaw,Zeke,1.612710e+09,GRD,26.0,34,16,18,0.471,...,1138,892,1056,865,845,959,512,39,894,1
1585,1627639,Zoi Dimitrakou,Zoi,1.611661e+09,WAS,30.0,2,0,2,0.000,...,1310,1039,1346,1460,1001,1531,512,39,1498,1

In [5]:
stats.to_csv("stats.csv")

In [6]:
import inspect
print(inspect.signature(LeagueDashPlayerStats))

(last_n_games='0', measure_type_detailed_defense='Base', month='0', opponent_team_id=0, pace_adjust='N', per_mode_detailed='Totals', period='0', plus_minus='N', rank='N', season='2024-25', season_type_all_star='Regular Season', college_nullable='', conference_nullable='', country_nullable='', date_from_nullable='', date_to_nullable='', division_simple_nullable='', draft_pick_nullable='', draft_year_nullable='', game_scope_simple_nullable='', game_segment_nullable='', height_nullable='', league_id_nullable='', location_nullable='', outcome_nullable='', po_round_nullable='', player_experience_nullable='', player_position_abbreviation_nullable='', season_segment_nullable='', shot_clock_range_nullable='', starter_bench_nullable='', team_id_nullable='', two_way_nullable='', vs_conference_nullable='', vs_division_nullable='', weight_nullable='', proxy=None, headers=None, timeout=30, get_request=True)

#- Compute and sort by advanced metrics:

In [7]:
stats.columns

Index(['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'NBA_FANTASY_PTS', 'DD2', 'TD3', 'WNBA_FANTASY_PTS', 'GP_RANK',
       'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK',
       'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK',
       'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK',
       'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK',
       'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK',
       'DD2_RANK', 'TD3_RANK', 'WNBA_FANTASY_PTS_RANK', 'TEAM_COUNT'],
      dtype='object')

In [8]:
#take a look at the data available, decide what story you want to tell

In [9]:
top_10_fgpct = stats.nlargest(10, 'FG_PCT')

In [10]:
top_10_fgpct[['PLAYER_NAME','FG_PCT']]

        PLAYER_NAME  FG_PCT
239            None     1.0
363            None     1.0
385            None     1.0
459            None     1.0
476            None     1.0
478            None     1.0
512            None     1.0
514            None     1.0
518            None     1.0
993  Jarnell Stokes     1.0

# Inspect Data- get to know it

## Univariate is a term commonly used in statistics to describe a type of data which consists of observations on only a single characteristic or attribute.

In [11]:


#check for any null/missing data
stats.isnull().sum()

PLAYER_ID                  0
PLAYER_NAME              525
NICKNAME                 525
TEAM_ID                  529
TEAM_ABBREVIATION        529
                        ...
NBA_FANTASY_PTS_RANK       0
DD2_RANK                   0
TD3_RANK                   0
WNBA_FANTASY_PTS_RANK      0
TEAM_COUNT                 0
Length: 67, dtype: int64

In [12]:
#how can we see the types of all columns
stats.dtypes

PLAYER_ID                  int64
PLAYER_NAME               object
NICKNAME                  object
TEAM_ID                  float64
TEAM_ABBREVIATION         object
                          ...
NBA_FANTASY_PTS_RANK       int64
DD2_RANK                   int64
TD3_RANK                   int64
WNBA_FANTASY_PTS_RANK      int64
TEAM_COUNT                 int64
Length: 67, dtype: object

In [13]:
stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1586 entries, 0 to 1585
Data columns (total 67 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   PLAYER_ID              1586 non-null   int64
 1   PLAYER_NAME            1061 non-null   object
 2   NICKNAME               1061 non-null   object
 3   TEAM_ID                1057 non-null   float64
 4   TEAM_ABBREVIATION      1057 non-null   object
 5   AGE                    1061 non-null   float64
 6   GP                     1586 non-null   int64
 7   W                      1586 non-null   int64
 8   L                      1586 non-null   int64
 9   W_PCT                  1586 non-null   float64
 10  MIN                    1586 non-null   float64
 11  FGM                    1586 non-null   float64
 12  FGA                    1586 non-null   float64
 13  FG_PCT                 1586 non-null   float64
 14  FG3M                   1586 non-null   float64
 15  FG3A                   1586 non-null   float64
 16  FG3_PCT                1586 non-null   float64
 17  FTM                    1586 non-null   float64
 18  FTA                    1586 non-null   float64
 19  FT_PCT                 1586 non-null   float64
 20  OREB                   1586 non-null   float64
 21  DREB                   1586 non-null   float64
 22  REB                    1586 non-null   float64
 23  AST                    1586 non-null   float64
 24  TOV                    1586 non-null   float64
 25  STL                    1586 non-null   float64
 26  BLK                    1586 non-null   float64
 27  BLKA                   1586 non-null   float64
 28  PF                     1586 non-null   float64
 29  PFD                    1586 non-null   float64
 30  PTS                    1586 non-null   float64
 31  PLUS_MINUS             1586 non-null   float64
 32  NBA_FANTASY_PTS        1586 non-null   float64
 33  DD2                    1586 non-null   int64
 34  TD3                    1586 non-null   int64
 35  WNBA_FANTASY_PTS       1586 non-null   float64
 36  GP_RANK                1586 non-null   int64
 37  W_RANK                 1586 non-null   int64
 38  L_RANK                 1586 non-null   int64
 39  W_PCT_RANK             1586 non-null   int64
 40  MIN_RANK               1586 non-null   int64
 41  FGM_RANK               1586 non-null   int64
 42  FGA_RANK               1586 non-null   int64
 43  FG_PCT_RANK            1586 non-null   int64
 44  FG3M_RANK              1586 non-null   int64
 45  FG3A_RANK              1586 non-null   int64
 46  FG3_PCT_RANK           1586 non-null   int64
 47  FTM_RANK               1586 non-null   int64
 48  FTA_RANK               1586 non-null   int64
 49  FT_PCT_RANK            1586 non-null   int64
 50  OREB_RANK              1586 non-null   int64
 51  DREB_RANK              1586 non-null   int64
 52  REB_RANK               1586 non-null   int64
 53  AST_RANK               1586 non-null   int64
 54  TOV_RANK               1586 non-null   int64
 55  STL_RANK               1586 non-null   int64
 56  BLK_RANK               1586 non-null   int64
 57  BLKA_RANK              1586 non-null   int64
 58  PF_RANK                1586 non-null   int64
 59  PFD_RANK               1586 non-null   int64
 60  PTS_RANK               1586 non-null   int64
 61  PLUS_MINUS_RANK        1586 non-null   int64
 62  NBA_FANTASY_PTS_RANK   1586 non-null   int64
 63  DD2_RANK               1586 non-null   int64
 64  TD3_RANK               1586 non-null   int64
 65  WNBA_FANTASY_PTS_RANK  1586 non-null   int64
 66  TEAM_COUNT             1586 non-null   int64
dtypes: float64(27), int64(37), object(3)
memory usage: 830.3+ KB

In [14]:
stats.describe()
stats.shape
#what are these? what do they show/mean?

(1586, 67)

In [15]:
stats.head(5)

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,TEAM_COUNT
0,52453,None,None,NaN,None,NaN,8,4,4,0.5,...,467,811,10,72,1122,84,227,39,85,1
1,52456,None,None,NaN,None,NaN,8,4,4,0.5,...,86,55,46,205,1122,269,227,39,248,1
2,52458,None,None,NaN,None,NaN,8,4,4,0.5,...,162,258,291,473,938,722,512,39,623,1
3,52449,None,None,NaN,None,NaN,8,4,4,0.5,...,467,642,1013,684,902,776,512,39,725,1
4,52455,None,None,NaN,None,NaN,8,4,4,0.5,...,937,301,366,875,702,717,512,39,781,1

# New DF

In [16]:
stats_25 = pd.read_csv("database_24_25.csv")
stats_25['Data'] = pd.to_datetime(stats_25['Data'])

In [17]:
stats_25.columns

Index(['Player', 'Tm', 'Opp', 'Res', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA',
       '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK',
       'TOV', 'PF', 'PTS', 'GmSc', 'Data'],
      dtype='object')

In [18]:
stats_25.dtypes

Player            object
Tm                object
Opp               object
Res               object
MP               float64
FG                 int64
FGA                int64
FG%              float64
3P                 int64
3PA                int64
3P%              float64
FT                 int64
FTA                int64
FT%              float64
ORB                int64
DRB                int64
TRB                int64
AST                int64
STL                int64
BLK                int64
TOV                int64
PF                 int64
PTS                int64
GmSc             float64
Data      datetime64[ns]
dtype: object

In [19]:
stats_25.describe()
stats_25.shape

(16512, 25)

In [20]:
stats_25.isnull().sum()

Player    0
Tm        0
Opp       0
Res       0
MP        0
FG        0
FGA       0
FG%       0
3P        0
3PA       0
3P%       0
FT        0
FTA       0
FT%       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
GmSc      0
Data      0
dtype: int64

In [21]:
#data ranges from 10-22 to 2-25

In [22]:
stats_25.info()
#identifiers - player,tm,opp,res
# usage / volume - mp, fga, 3pa, fta, tov
# efficiency - fg%, 3p%, ft%  (ts% claculate)
# counting / production - pts, trb(orb+drb), ast,stl,blk,pf (TRB calculate )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16512 entries, 0 to 16511
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  16512 non-null  object
 1   Tm      16512 non-null  object
 2   Opp     16512 non-null  object
 3   Res     16512 non-null  object
 4   MP      16512 non-null  float64
 5   FG      16512 non-null  int64
 6   FGA     16512 non-null  int64
 7   FG%     16512 non-null  float64
 8   3P      16512 non-null  int64
 9   3PA     16512 non-null  int64
 10  3P%     16512 non-null  float64
 11  FT      16512 non-null  int64
 12  FTA     16512 non-null  int64
 13  FT%     16512 non-null  float64
 14  ORB     16512 non-null  int64
 15  DRB     16512 non-null  int64
 16  TRB     16512 non-null  int64
 17  AST     16512 non-null  int64
 18  STL     16512 non-null  int64
 19  BLK     16512 non-null  int64
 20  TOV     16512 non-null  int64
 21  PF      16512 non-null  int64
 22  PTS     16512 non-null  int64
 23  GmSc    16512 non-null  float64
 24  Data    16512 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(15), object(4)
memory usage: 3.1+ MB

In [25]:
stats_25
#start engineering features we want
#explore how those features behave (distirbutions / relationships)
#formulate and test 
#visalize and communicate

,Player,Tm,Opp,Res,MP,FG,FGA,FG%,3P,3PA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,Data
0,Jayson Tatum,BOS,NYK,W,30.30,14,18,0.778,8,11,...,4,4,10,1,1,1,1,37,38.1,2024-10-22
1,Anthony Davis,LAL,MIN,W,37.58,11,23,0.478,1,3,...,13,16,4,1,3,1,1,36,34.0,2024-10-22
2,Derrick White,BOS,NYK,W,26.63,8,13,0.615,6,10,...,3,3,4,1,0,0,1,24,22.4,2024-10-22
3,Jrue Holiday,BOS,NYK,W,30.52,7,9,0.778,4,6,...,2,4,4,1,0,0,2,18,19.5,2024-10-22
4,Miles McBride,NYK,BOS,L,25.85,8,10,0.800,4,5,...,0,0,2,0,0,1,1,22,17.8,2024-10-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16507,Emoni Bates,CLE,WAS,W,5.18,0,2,0.000,0,2,...,0,0,2,0,0,0,2,0,-0.8,2025-02-07
16508,A.J. Green,MIL,ATL,L,20.75,1,5,0.200,0,2,...,1,1,1,0,0,0,2,2,-0.9,2025-02-07
16509,Kenrich Williams,OKC,TOR,W,16.70,0,5,0.000,0,3,...,1,3,2,0,0,1,0,0,-1.4,2025-02-07
16510,Tyrese Martin,BRK,MIA,W,20.70,1,5,0.200,0,4,...,5,5,1,0,0,3,2,2,-2.7,2025-02-07
16511,Eric Gordon,PHI,DET,L,10.35,0,4,0.000,0,3,...,3,3,2,0,0,3,1,0,-3.9,2025-02-07

## Descriptive Analytics
(“What happened?” / Summary & reporting)
These features help you summarize and track performance over time or across groups.

# Normalized rates
PTS_per36, AST_per36, REB_per36: raw counts scaled to 36 minutes.

# Efficiency splits
TS% (True Shooting%), eFG%, plus separate 2P% and 3P% for deeper shooting breakdowns.

# Rolling aggregates
rolling_PTS_avg_5g: 5‑game moving average of points.
rolling_TS%_10g: last‑10‑game shooting efficiency.

# Cumulative totals
cum_PTS_season: running total of points through each date.

# Situational flags
is_clutch: game within 5 points in final 5 minutes (0/1).
home_game vs. away_game binary.

# Simple ratios
AST_to_TOV: assists divided by turnovers.
ORB_rate or DRB_rate: percentage of available rebounds grabbed.

In [26]:
#-------

# Classification / Regression
(“What will happen?” / Predict outcomes or values)
Here, you build features that carry predictive signal for a target (win/loss, next‑game PTS, salary band, etc.).

# Usage & possession metrics
Usage_Rate: share of team possessions used by the player.
 ORtg / DRtg: individual offensive/defensive ratings.

# Advanced composites
PER (Player Efficiency Rating), RAPTOR, VORP — league‑standard impact estimates.

# Interaction terms
 MP × TS%: captures volume × efficiency synergy.
3PA × 3P%: high‑volume shooters weighted by accuracy.
# Lagged and trend features
PTS_last_game, AST_rolling_diff: difference between last two rolling averages.
game_to_game_std_PTS: volatility in scoring—predict consistency outcomes.

# Contextual encodings
One‑hot position (PG/SG/SF/PF/C).
opp_def_rank_bin: opponent defense rating bucketed (top‑5, middle, bottom‑5).
# Team‑level joins
team_pace, team_off_rating joined back to individual lines so model knows system context.

In [27]:
# -----

# 3. Clustering / Profiling
(“How do entities group?” / Player archetypes & segmentation)
Features here feed unsupervised algorithms (k‑means, hierarchical clustering, UMAP) to reveal natural groupings.

# Profile vectors
[Usage_Rate, TS%, AST_rate, REB_rate, STL_rate, BLK_rate] normalized per‑36 or per‑100 possessions.

# Shooting‑mix percentages
pct_rim_shots, pct_midrange, pct_3pt_attempts: the share of each shot zone.

# Playstyle ratios
ast_to_usage, blk_to_usage, stl_to_usage: defensive vs. offensive tendencies.

# Dimensionality reduction inputs
PCA on the above rates to get “style components” (e.g. Component 1 = paint‑heavy vs. perimeter).

# Role flags
starter_flag (MP > 25 minutes) vs. bench_flag.
clutch_specialist if clutch FG% > season average + threshold.

# Synergy / lineup metrics
net_rating_when_on_court, teammate_pass_share: how a player fits with others.

In [28]:
#-----

# Picking & testing
## Match features to your goal:

Descriptive needs simple aggregates & rates.

Predictive tasks thrive on interaction, context flags, and lagged signals.

Clustering leans on normalized style vectors and dimensionality‑reduced representations.

## Quickly prototype:
 run a tiny regression or clustering on a subset to see which features carry signal.

## Iterate & refine
 drop the noisy ones, enrich the strong ones, and always ask “does this help me answer my core question?”